name: CI

on:
  pull_request:
    branches:
      - main

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always

jobs:
  fix:
    permissions:
      contents: write

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy,rustfmt

      - name: Setup cache for Rust
        uses: Swatinem/rust-cache@v2

      - name: Fix Rust code
        run: |
          cargo clippy --locked --fix --allow-dirty
          cargo fmt

      - name: Commit if needed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: apply formatter/linter changes"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"

  check:
    needs: [fix]

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Setup cache for Rust
        uses: Swatinem/rust-cache@v2

      - name: Build
        run: cargo build --locked

      - name: Test
        run: cargo test --locked

      - name: Lint
        run: cargo clippy --locked
